name: Coverage

on:
  pull_request:
    branches: [master]
    paths: ["committracker/**", "tests/**", ".github/workflows/cov.yml"]
  push:
    branches: [master]
    paths: ["committracker/**", "tests/**", ".github/workflows/cov.yml"]
    tags: "*"

jobs:
  determine-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          pip install .[dev]
      - name: Test with pytest and create coverage report
        run: pytest --cov=committracker --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
