name: Coverage

on:
  pull_request:
    branches: [main]
    paths: ["committracker/**", "tests/**", ".github/workflows/cov.yml"]
  push:
    branches: [main]
    paths: ["committracker/**", "tests/**", ".github/workflows/cov.yml"]
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Run Tests with Coverage
        run: pytest --cov=committracker --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
