name: Publish

on:
  push:
    tags: "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Install build and publish dependencies
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
