name: Coverage

on:
  pull_request:
    branches: [main]
    paths: ["committracker/**", "tests/**", ".github/workflows/cov.yml"]
  push:
    branches: [main]
    paths: ["committracker/**", "tests/**", ".github/workflows/cov.yml"]
    tags: "*"

jobs:
  determine-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]
      - name: Test with pytest and create coverage report
        run: pytest --cov=committracker --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
