name: Tests

on:
  pull_request:
    branches: [master]
    paths:
      [
        "committracker/**",
        "tests/**",
        "pyproject.toml",
        ".github/workflows/test.yml",
      ]
  push:
    branches: [master]
    paths:
      [
        "committracker/**",
        "tests/**",
        "pyproject.toml",
        ".github/workflows/test.yml",
      ]
    tags: "*"

jobs:
  run-tests:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          pip install -e .[dev]
      - name: Test with pytest
        run: pytest --cov=committracker
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
